[tool.poetry]
name = "json-pointer"
version = "0.1.0"
description = "Implements RFC 6901 JSON pointers, and json-schema draft relative pointer resolution."
authors = ["Tristan Sweeney <sweeneytri@gmail.com>"]
license = "GNU Lesser General Public License v3.0"

packages = [
    { include = "json-pointer", from="src" },
]

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.dev-dependencies]
black = "^22.10.0"
isort = "^5.10.1"
mypy = "^0.991"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
