# https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
name: "CI"

on: [push, pull_request]

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
    
      - name: Set package version
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry version $(git describe --tags --abbrev=0)
       
    - name: Install and run tests
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry install -E cli
        poetry run pytest --cov=fast_json_pointer --cov-report lcov tests/ --doctest-modules src/

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        path-to-lcov: coverage.lcov
        github-token: ${{ secrets.GITHUB_TOKEN }}

  build-n-publish:
    name: "Build and publish Python distributions to PyPI and TestPyPI"
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
    
      - name: Set package version
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry version $(git describe --tags --abbrev=0)
       
      - name: Install pypa/build
        run: python -m pip install build --user

      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
      
      - name: "Publish distribution to PyPI"
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: '${{ secrets.PYPI_API_TOKEN }}'
