# https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
name: "CI"

on: [push, pull_request]

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'
    
      - name: Install package under test
        run: poetry install -E cli

      - name: Run tests
        run: poetry run pytest --cov=fast_json_pointer --cov-report lcov tests/ --doctest-modules src/

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: coverage.lcov
          github-token: ${{ secrets.GITHUB_TOKEN }}

  test-publish:
    name: "TestPyPI"
    if: "! startsWith(github.ref, 'refs/tags/v')"
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
          cache: 'poetry'
    
      #- name: Set package version
      #  run: poetry version $(git rev-parse --short HEAD)

      - name: Build a binary wheel and a source tarball
        run: poetry build

      - name: Publish to test PyPI
        run: |
          poetry config repo.test-pypi https://test.pypi.org/legacy/
          poetry config pypi-token.test-pypi '${{ secrets.TEST_PYPI_API_TOKEN }}'
          poetry publish --repository=test

  publish:
    name: "PyPI"
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
          cache: 'poetry'
    
      - name: Set package version
        run: poetry version $(git describe --tags --abbrev=0)

      - name: Build a binary wheel and a source tarball
        run:  poetry build

      - name: Create github release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*

      - name: Publish to PyPI
        run: poetry publish --username=__token__
        env:
          PYPI_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
 
