name: Publish to PyPI

on:
  workflow_call:
    inputs:
      repo:
        required: false
        type: string
        default:  https://upload.pypi.org/legacy/
      gh-release:
        required: false
        type: boolean
        default: false
    secrets:
      pypi-token:
        required: true

jobs:
  publish:
    name: "Publish PyPI"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
          cache: 'poetry'
    
      - name: Set package version
        run: poetry version $(git describe --tags --abbrev=0)

      - name: Build a binary wheel and a source tarball
        run: poetry build

      - name: Create github release
        if: inputs.gh-release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*

      - name: Publish to PyPI
        run: |
          poetry config repo.target-pypi ${{ inputs.repo }}
          poetry config pypi-token.target-pypi '${{ secrets.pypi-token }}'
          poetry publish --skip-existing --repository=target-pypi