on: ["push", "pull_request"]

name: Test

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Install and run tests
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry install
        poetry run pytest --cov=fast_json_pointer --cov-report lcov tests/

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        path-to-lcov: coverage.lcov
        github-token: ${{ secrets.GITHUB_TOKEN }}